---
name: Build Linux Kernel

on:
  workflow_call:
    inputs:
      config:
        description: Target device config (e.g., coreboot-config-x230)
        required: true
        type: string

      use_arm_runner:
        description: Use ARM runner (ubuntu-24.04-arm) instead of ubuntu-latest
        required: false
        default: false
        type: boolean
permissions:
  contents: read
  packages: write

jobs:
  build-coreboot:
    name: Build coreboot (${{ inputs.config }})
    runs-on: ${{ inputs.use_arm_runner && 'ubuntu-24.04-arm' || 'ubuntu-latest' }}
    steps:
      - name: Aggressive cleanup
        uses: bbusse/github-workflows/.github/actions/aggressive-cleanup@dev

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Checkout image-builder
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: 'OpsBoost/image-builder'
          ref: 'dev'
          path: 'image-builder'

      - name: Build coreboot
        env:
          CONFIG: ${{ inputs.config }}
        run: |
          set -eu
          sudo ./image-builder/image-builder install
          BUILD_USE_CONTAINER=1 \
            image-builder build coreboot "$CONFIG"
