---
name: Build Linux Kernel

on:
  workflow_call:
    inputs:
      config:
        description: Target kernel config (e.g., kernel-config-x230)
        required: true
        type: string

permissions:
  contents: read
  packages: write

jobs:
  build-linux-kernel:
    runs-on: ubuntu-latest
    steps:
      - name: Aggressive cleanup
        run: |
          sudo rm -rf /usr/lib/jvm /usr/share/dotnet /usr/share/swift \
                      /usr/local/.ghcup /usr/local/julia* /usr/local/lib/android \
                      /usr/local/share/chromium /opt/microsoft /opt/google \
                      /opt/az /usr/local/share/powershell /opt/hostedtoolcache || true
          docker system prune -af || true
          docker builder prune -af || true
          df -h

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Checkout image-builder
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: 'OpsBoost/image-builder'
          ref: 'dev'
          path: 'image-builder'

      - name: Build Linux Kernel
        run: |
          sudo ./image-builder/image-builder install
          BUILD_USE_CONTAINER=1 \
          image-builder build linux-kernel ${{ inputs.config }}
          echo "${{ secrets.GITHUB_TOKEN }}" | podman login ghcr.io -u $GITHUB_ACTOR --password-stdin
          podman push ghcr.io/bbusse/linux-kernel-${{ inputs.config }}:latest

      - name: Extract kernel image from build container
        uses: bbusse/container-extract@v1
        id: extract-image
        with:
          image: ghcr.io/bbusse/linux-kernel-${{ inputs.config }}:latest
          paths: usr/src/linux/Image-${{ inputs.config }}
          platform: linux/arm64

      - name: Extract kernel image checksum from build container
        uses: bbusse/container-extract@v1
        id: extract-checksum
        with:
          image: ghcr.io/bbusse/linux-kernel-${{ inputs.config }}:latest
          paths: usr/src/linux/Image-${{ inputs.config }}.sha384
          platform: linux/arm64

      - name: Move extracted files
        run: |
          mv "${{ steps.extract-image.outputs.destination }}/Image-${{ inputs.config }}" "Image-${{ inputs.config }}"
          mv "${{ steps.extract-checksum.outputs.destination }}/Image-${{ inputs.config }}.sha384" "Image-${{ inputs.config }}.sha384"

      - name: Upload kernel image artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: linux-kernel-${{ inputs.config }}
          path: |
            Image-${{ inputs.config }}
            Image-${{ inputs.config }}.sha384
