name: FreeBSD Package Build

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      artifact_name:
        required: true
        type: string

jobs:
  build-freebsd:
    runs-on: ubuntu-latest
    name: FreeBSD Build
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: FreeBSD Build
        uses: vmactions/freebsd-vm@77ed28d336d03fe19a3f4f7266c1d2c4714dd79d # v1.5.2
        id: build
        with:
          usesh: true
          prepare: |
            pkg install -y curl go

          run: |
            freebsd-version
            pwd
            ls -lah
            go build -o ${{ inputs.artifact_name }}
            tar -cJvf ${{ inputs.artifact_name }}-freebsd-amd64-latest.tar.xz ${{ inputs.artifact_name }}
            ls -lah

      - name: Upload artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{ inputs.artifact_name }}-freebsd-amd64-latest.tar.xz
          path: ${{ inputs.artifact_name }}-freebsd-amd64-latest.tar.xz
